apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mysql
  namespace: roboshop
  # These are replica set labels.
  labels:
    project: roboshop
    component: mysql
    tier: db
spec:
  replicas: 1
  selector:
  # These labels are used to select pods.
    matchLabels:
      project: roboshop
      component: mysql
      tier: db
  # pod definition
  template:
    metadata: 
      labels:
        project: roboshop
        component: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: kattika/mysql:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: mysql
    tier: db
  ports:
    - protocol: TCP
      port: 3306 #service port
      targetPort: 3306 #container port